### ISSUE TITLE
Create first version of the frontend testing workshop

### ISSUE THREAD

**Issue by ep-cc** [ep-cc/frontend-testing-workshop#1]
# Overview
So far we did not have hard skill workshops for job hunters. Now we are planning to create a few. This one is about testing frontend code using Javascript testing frameworks.

# TODOs
- [x] Initialize repository: Readme.md, folder structure
- [x] Create slides
    - [x]  Frontend testing overview
    - [x] Unit testing with Vitest and React testing library
- [x] Add a small react project to test
- [x] Add test examples (sync, async, stateless, stateful, mock fetch, react router)
- [x] Add tasks for the students
